### ISSUE TITLE
Unresolved reference: DrawableResource ; Unresolved reference: kotlinproject

### ISSUE THREAD

**Issue by SamuelMarks** [kotlin-hands-on/get-started-with-cm#1]
Just downloaded Android Studio and gave your project a whirl. Opening up `ComposeDemoStage4`, upgrading (popup suggested)

```diff
diff --git a/ComposeDemoStage4/gradle/libs.versions.toml b/ComposeDemoStage4/gradle/libs.versions.toml
index 0f27728..01f5220 100644
--- a/ComposeDemoStage4/gradle/libs.versions.toml
+++ b/ComposeDemoStage4/gradle/libs.versions.toml
@@ -1,5 +1,5 @@
 [versions]
-agp = "8.1.4"
+agp = "8.3.0"
 android-compileSdk = "34"
 android-minSdk = "24"
 android-targetSdk = "34"
```

Then tried to run but got some errors:
```
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:23:8 Unresolved reference: kotlinproject
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:28:40 Unresolved reference: DrawableResource
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:33:69 Unresolved reference: DrawableResource
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:46:49 Unresolved reference: Res
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:47:52 Unresolved reference: Res
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:48:59 Unresolved reference: Res
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:49:55 Unresolved reference: Res
e: file:///get-started-with-cm/ComposeDemoStage4/composeApp/src/commonMain/kotlin/App.kt:50:51 Unresolved reference: Res
```

![image](https://github.com/kotlin-hands-on/get-started-with-cm/assets/807580/f0d95c2d-0054-4e28-a418-ff8768f499ed)

Haven't touched Kotlin or Android Studio in years so maybe I'm missing a configuration? - Like making things relative to specific directory? - I tried `import composeapp.generated.resources.Res` and `import generated.resources.Res` also.

Is there a separate trigger to create the `generated` directory?

Not sure what to do next. Planning to use Kotlin Multiplatform for my next open-source cross-platform GUI project.

Thanks for suggestions

**Comment by dennisfen** [comment]
Same issue on Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 21, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
